#
# Module manifest for module 'IntuneFirewallMigration'
#
# Generated by: Nick Benton
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule      = 'FirewallRuleMigration.psm1'

    # Version number of this module.
    ModuleVersion   = '0.2'

    # ID used to uniquely identify this module
    GUID            = '70020e90-cdfd-449f-8f8d-9d5eb71eb667'

    # Author of this module
    Author          = 'Kevin Hui, Tessy Emadoye, Nick Benton'

    # Company or vendor of this module
    CompanyName     = 'Microsoft, oddsandendpoints.co.uk'

    # Copyright statement for this module
    Copyright       = '(c) 2019 Microsoft. All rights reserved.'

    # Description of the functionality provided by this module
    Description     = 'PowerShell cmdlet suite to support automation of migrating Windows firewall rules to Microsoft Intune'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @('Microsoft.Graph.Authentication', 'ImportExcel')

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module
    # FunctionsToExport = 'Get-Function'

    # Cmdlets to export from this module
    CmdletsToExport = @('Get-FirewallData', 'Export-NetFirewallRule', 'Send-IntuneFirewallRulesPolicy', 'ConvertTo-IntuneFirewallRule', 'New-IntuneFirewallRule', 'Connect-ToGraph', 'ConvertTo-IntuneSCFirewallRule')

    # Variables to export from this module
    # VariablesToExport = '*'

    # Aliases to export from this module
    # AliasesToExport = ''

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess
    PrivateData     = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = @('Intune', 'Firewall', 'Migration')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/ennnbeee/IntuneFirewallMigration/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/ennnbeee/IntuneFirewallMigration'

            # A URL to an icon representing this module.
            IconUri    = 'https://raw.githubusercontent.com/ennnbeee/IntuneFirewallMigration/main/img/ifm-icon.png'
        }

    }

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}